- platform: yr
- platform: ring
  monitored_conditions:
    - battery
    - last_motion
    - last_activity
    - volume
    - last_ding
    - wifi_signal_strength
    - wifi_signal_category
    
#- platform: template
#  sensors:
#    softener_watts:
#      friendly_name: "Water Softener Watts"
#      unit_of_measurement: "w"
#      value_template: '{% if states.switch.wemo_insight %}{{ states.switch.wemo_insight.attributes.current_power_w }}{% else %}Off{% endif %}'

- platform: template
  sensors:
    dehumidifier_watts:
      friendly_name: "Dehumidifier Watts"
      unit_of_measurement: "w"
      value_template: '{% if states.switch.wemo_insight %}{{ states.switch.wemo_insight.attributes.current_power_w }}{% else %}Off{% endif %}'

    
- platform: template
  sensors:
    number_of_lights_on:
      value_template: >-
        {% for state in states if ( 'light' in state.entity_id and state.domain in ['light','switch'] and state.state == 'on' ) -%}
              {% if loop.last -%}
              {{ loop.index }}
              {%- endif %}
              {% else %}
                  0
        {%- endfor %}
      entity_id: sensor.time
      
- platform: template
  sensors:
# If either "device" reports as home, this sensor returns 'on' #
      current_activity:
        friendly_name: 'Current Activity'
        value_template: '{{ states.remote.living_room_harmony.attributes.current_activity }}'
        
      current_activity2:
        friendly_name: 'Current Activity'
        value_template: '{{ states.remote.bedroom_harmony.attributes.current_activity }}'



      jor_home:
        entity_id:
          - device_tracker.galaxy_note8
          - device_tracker.jphone
          - device_tracker.galaxynote8
        value_template: >-
          {{ is_state('device_tracker.galaxy_note8', 'home')
             or is_state('device_tracker.jphone', 'home')
             or is_state('device_tracker.galaxynote8', 'home') }}
      cella_home:
        entity_id:
          - device_tracker.cella_gpslogger
          - device_tracker.mossella
        value_template: >-
          {{ is_state('device_tracker.cella_gpslogger', 'home')
             or is_state('device_tracker.mossell', 'home') }}
      everyone_home:
        entity_id:
          - device_tracker.galaxy_note8
          - device_tracker.galaxynote8
          - device_tracker.cella_gpslogger
          - device_tracker.mossella
        value_template: >-
           {{ is_state('device_tracker.galaxy_note8', 'home')
             or is_state('device_tracker.jphone', 'home')
             or is_state('device_tracker.galaxynote8', 'home')
             or is_state('device_tracker.mossella', 'home')
             or is_state('device_tracker.cellas_gpslogger', 'home') }}
      jor_not_home:
        entity_id:
          - device_tracker.galaxy_note8
          - device_tracker.galaxynote8
        value_template: >-
          {{ is_state('device_tracker.galaxy_note8', 'not_home')
             or is_state('device_tracker.galaxynote8', 'not_home') }}

      moss_not_home:
        entity_id:
          - device_tracker.cella_gpslogger
          - device_tracker.mossella
          - device_tracker.mossella_2
        value_template: >-
          {{ is_state('device_tracker.cella_gpslogger', 'not_home')
             or is_state('device_tracker.mossella', 'not_home')
             or is_state('device_tracker.mossella_2', 'not_home')}}
             
      center_map_on:
        value_template: >-
          {% set center = states.input_select.center_map_on.state %}
          {% if center == "Jor"%}
            {% set lat = states.device_tracker.jphone.attributes.latitude %}
            {% set long = states.device_tracker.jphone.attributes.longitude %}
          {% elif center == "Cella"%}
            {% set lat = states.device_tracker.cella_gpslogger.attributes.latitude %}
            {% set long = states.device_tracker.cella_gpslogger.attributes.longitude %}
          {% else %}
            {% set lat = states.device_tracker.jphone.attributes.latitude %}
            {% set long = states.device_tracker.jphone.attributes.longitude %}
          {% endif %}
          {{ [lat,long]|join(',') }}
      
      friends_home:
        entity_id:
          - device_tracker.android73fa1eff65de2462
          - device_tracker.benjaminsiphone
        value_template: >-
           {{ is_state('device_tracker.benjaminsiphone', 'home')
             or is_state('device_tracker.android73fa1eff65de2462', 'home') }}
             
- platform: google_travel_time
  api_key: AIzaSyCiFBtPHORegLgaUuzy4Cs8Dr2OyEbDjlw
  name: google_travel_time_jor_to_cella
  origin: device_tracker.galaxy_note8
  destination: device_tracker.cella_gpslogger
  
- platform: google_travel_time
  api_key: AIzaSyCiFBtPHORegLgaUuzy4Cs8Dr2OyEbDjlw
  name: google_travel_time_cella_to_jor
  origin: device_tracker.cella_gpslogger
  destination: device_tracker.galaxy_note8
  
- platform: etherscan
  address: !secret etherscan_add
  token: APPC
  token_address: !secret etherscan_token
  
- platform: haveibeenpwned
  email:
      - jordanielafontaine@gmail.com
      - marcellalafontaine@gmail.com
      - j.lafontaine@snhu.edu
      - m.lafontaine@snhu.edu
      - jlafontaine.it@gmail.com
      - mmuscate@gmail.com
      - banjordium@gmail.com
      - jordan.lafontaine@gmail.com
      - jordanielafontaine@hotmail.com
      - jordan.lafontaine@hotmail.com
    
  
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_use_percent
      arg: /var/log
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
    - type: processor_use
    - type: swap_use_percent
    - type: swap_use
    - type: swap_free
    - type: last_boot
    - type: since_last_boot
    - type: network_in
      arg: wlan0
    - type: network_out
      arg: wlan0
    - type: packets_in
      arg: wlan0
    - type: packets_out
      arg: wlan0
    - type: ipv4_address
      arg: wlan0
    - type: ipv6_address
      arg: wlan0
      
- platform: steam_online
  api_key: !secret steamapi
  accounts: 
    - 76561198020748567
    - 76561198028167709
    - 76561198116371201
    - 76561198055768726
    - 76561198014880362
    - 76561197960457718
    - 76561197980544086
    - 76561197976189854
    - 76561198054144074
    - 76561198030775146
    - 76561198297273260
    
    
- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  # If errors occur, remove degree symbol below
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) }}'
